export default function Home() {
  return (
    // 다시 되돌려놓기
    <div className="text-blue bg-violet-8">
      <div>Top</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
      <div>Taskify</div>
    </div>
  );
}
